### ISSUE TITLE
Closed loop LineStrings

### ISSUE THREAD

**Issue by DenisCarriere** [sharedstreets/sharedstreets-conflator#8]
### distanceToNextRef is required if outboundBearing is present

Attempted to use the conflator on the entire dataset of the Toronto Centreline. 😢 

```
sharedstreets-conflator CENTRELINE_WGS84.shp
Error: distanceToNextRef is required if outboundBearing is present
    at locationReference (/Users/mac/.config/yarn/global/node_modules/sharedstreets/index.js:
364:15)
    at Object.geometry (/Users/mac/.config/yarn/global/node_modules/sharedstreets/index.js:101:28)
    at geometry (/Users/mac/.config/yarn/global/node_modules/sharedstreets-conflator/index.js:86:33)
    at geometry.next (<anonymous>)
    at Object.conflator (/Users/mac/.config/yarn/global/node_modules/sharedstreets-conflator/index.js:46:20)
    at conflator.next (<anonymous>)
    at /Users/mac/.config/yarn/global/node_modules/sharedstreets-conflator/bin/sharedstreets-conflator.js:70:20
    at Generator.next (<anonymous>)
    at fulfilled (/Users/mac/.config/yarn/global/node_modules/sharedstreets-conflator/bin/sharedstreets-conflator.js:5:58)
    at <anonymous>
```

**Comment by DenisCarriere** [comment]
Issue was roads closing on itself.

GeoJSON => https://gist.github.com/3524bb68d6026cacc08a0b80652bc691

## Questions @kpwebb 

- Would the `distanceToNextRef` be 0 in this case? Since both the `start` & `end` intersections are on the same coordinate, or should be the distance of the geometry?

![image](https://user-images.githubusercontent.com/550895/36405057-6b81541c-15bc-11e8-86fb-8ca7ff7137b4.png)

**Comment by kpwebb** [comment]
@DenisCarriere  this should be should be the distance along geometry.

**Comment by kpwebb** [comment]
This brings up some interesting points though: the reference should be intersection to intersection (topology), not based on the geometry. the geometry is self-intersecting, but the road isn't.  I'm working on post-processing step that merges linestring derived references together to get actual SS references, but we should strategize on where this fits into the processing. maybe upstream of the geom/intersection/reference generation.

**Comment by kpwebb** [comment]
FYI, this might be a useful reference for what's happening in the builder app with OSM:

https://github.com/sharedstreets/sharedstreets-builder/blob/master/src/main/java/io/sharedstreets/tools/builder/transforms/BaseSegments.java#L181

**Comment by kpwebb** [comment]
Just looked at Toronto Centerline data and not clear that it contains sufficient information to extract topology for intersecting geometries. Looks like roads that cross each other but don't intersect share common to/from node ids (FNODE & TNODE), and don't contain any zlevel information. Going to ask the Toronto folks for ideas on how to resolve this.

**Comment by DenisCarriere** [comment]
> this should be should be the distance along geometry.

👍 sounds good, next is having our length calculations match (~35cm off between Javascript/Java implementation), currently using Haversine Formula for the length of the geometry. I could calculate the length using the `rhumb` distance, maybe it will match.

Used this geometry to calculate the ~35cm offset between both libraries.

```js
const line = [[-74.006449, 40.739405000000005], [-74.00790070000001, 40.7393884], [-74.00805100000001, 40.7393804]];

sharedstreets.distanceToNextRef(line) //=> 13501
// => Java Implementation => 13536
```

> Just looked at Toronto Centerline data and not clear that it contains sufficient information to extract topology for intersecting geometries. 

Nope, agreed, however for custom data, I'm not too sure if it's best to split data or merge linestrings together simply to make the topology work. From my point of view, simply having a SharedStreets Geometry Hash ID would be good enough, no need to dive further.

> Going to ask the Toronto folks for ideas on how to resolve this.

Every City will be like this, I think we would need to lower our expectations of custom data quality and have a "simple" implementation and an advance "topology" implementation.

Currently the `sharedstreets-conflator` is processing the Geometry as is and extracting the Start & End nodes as Intersections. Anything more then that should be considered "advanced" (topology) and to build a general purpose tool that would handled all sorts of custom datasets would take some time to developpe.

>  I'm working on post-processing step that merges linestring derived references together to get actual SS references, 

Don't know how we would handle this using Lambda function since RAM or storage is not shared between message queues.

**Comment by DenisCarriere** [comment]
Moved to https://github.com/sharedstreets/sharedstreets-js/issues/16
